Update README.md
`--set` will do implicit type conversion by transforming to json. For an Amazon Account with digits only it will cause 
```
Error: render error in "registry-creds/templates/secrets_ecr.yaml": template: registry-creds/templates/secrets_ecr.yaml:14:45: executing "registry-creds/templates/secrets_ecr.yaml" at <b64enc>: wrong type for value; expected string; got float64
```
`--set-string` set explizit string as type